---
- hosts: all
  sudo: yes
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get -y install python
